source 'http://rubygems.org'

gem 'rake'
gem 'rails', '~> 3.2'

gem 'iconv'
gem 'activesupport'
gem 'therubyracer'
gem 'mysql2','0.3.12b4'
gem 'mongodb'
gem 'devise'
gem 'devise_ldap_authenticatable', :path => 'lib/devise_ldap_authenticatable'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'capistrano_colors'
gem 'passenger'
gem 'rb-readline'
gem 'dynamic_form'
gem 'acts_as_tree'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'spinjs-rails'
gem 'font-awesome-rails', '~> 4.1.0'
gem 'eco'
gem 'minitest'
gem 'ckeditor'#, :git => 'https://github.com/galetahub/ckeditor'
gem 'paperclip'
gem 'fileutils'
gem 'pdf-reader'
gem 'wicked_pdf'
gem 'ensure-encoding'
gem 'ruby-rtf'
gem 'nokogiri'
gem 'htmlentities'
gem 'loofah'
gem 'i18n_generators'
gem 'i18n-js'
gem 'resque'
gem 'parallel'
#gem 'delayed_job'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'anemone'
gem 'thin'
gem 'thinking-sphinx', '3.1.1' #:path => 'lib/thinking-sphinx'#, '3.0.2',
gem 'ts-delayed-delta', :git => 'git://github.com/onland/ts-delayed-delta.git', :require => 'thinking_sphinx/deltas/delayed_delta' 
gem 'chardet'
gem 'difflcs'
gem 'plupload-rails'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'jquery-tmpl-rails'
gem 'pdfjs-rails', :git => 'git://github.com/Empact/pdfjs-rails.git'
gem 'color'
gem 'sprockets'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'compass-rails'
  gem 'therubyracer', :platform => :ruby
  gem 'bootstrap-sass', '~> 3.2.0'
end

group :test do
  gem 'turn', :require => false
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
end

gem 'rspec-rails', :group => [:development, :test]
